const { getGithubTrendingContent } = require('./github')

const actions = [
  [getGithubTrendingContent('https://github.com/trending?since=daily'), 'github_trending_daily'],
  [getGithubTrendingContent('https://github.com/trending?since=weekly'), 'github_trending_weekly'],
  [getGithubTrendingContent('https://github.com/trending?since=monthly'), 'github_trending_monthly'],
  [getGithubTrendingContent('https://github.com/trending/python?since=daily'), 'github_python_daily'],
  [getGithubTrendingContent('https://github.com/trending/python?since=weekly'), 'github_python_weekly'],
  [getGithubTrendingContent('https://github.com/trending/python?since=monthly'), 'github_python_monthly'],
  [getGithubTrendingContent('https://github.com/trending/vue?since=daily'), 'github_vue_daily'],
  [getGithubTrendingContent('https://github.com/trending/vue?since=weekly'), 'github_vue_weekly'],
  [getGithubTrendingContent('https://github.com/trending/vue?since=monthly'), 'github_vue_monthly'],
  [getGithubTrendingContent('https://github.com/trending/go?since=daily'), 'github_go_daily'],
  [getGithubTrendingContent('https://github.com/trending/go?since=weekly'), 'github_go_weekly'],
  [getGithubTrendingContent('https://github.com/trending/go?since=monthly'), 'github_go_monthly'],
  [getGithubTrendingContent('https://github.com/trending/java?since=daily'), 'github_java_daily'],
  [getGithubTrendingContent('https://github.com/trending/java?since=weekly'), 'github_java_weekly'],
  [getGithubTrendingContent('https://github.com/trending/java?since=monthly'), 'github_java_monthly'],
  [getGithubTrendingContent('https://github.com/trending/typescript?since=daily'), 'github_typescript_daily'],
  [getGithubTrendingContent('https://github.com/trending/typescript?since=weekly'), 'github_typescript_weekly'],
  [getGithubTrendingContent('https://github.com/trending/typescript?since=monthly'), 'github_typescript_monthly'],
  [getGithubTrendingContent('https://github.com/trending/javascript?since=daily'), 'github_javascript_daily'],
  [getGithubTrendingContent('https://github.com/trending/javascript?since=weekly'), 'github_javascript_weekly'],
  [getGithubTrendingContent('https://github.com/trending/javascript?since=monthly'), 'github_javascript_monthly'],
  [getGithubTrendingContent('https://github.com/trending/html?since=daily'), 'github_html_daily'],
  [getGithubTrendingContent('https://github.com/trending/html?since=weekly'), 'github_html_weekly'],
  [getGithubTrendingContent('https://github.com/trending/html?since=monthly'), 'github_html_monthly'],
  [getGithubTrendingContent('https://github.com/trending/css?since=daily'), 'github_css_daily'],
  [getGithubTrendingContent('https://github.com/trending/css?since=weekly'), 'github_css_weekly'],
  [getGithubTrendingContent('https://github.com/trending/css?since=monthly'), 'github_css_monthly'],
  [getGithubTrendingContent('https://github.com/trending/unknown?since=daily'), 'github_unknown_daily'],
  [getGithubTrendingContent('https://github.com/trending/unknown?since=weekly'), 'github_unknown_weekly'],
  [getGithubTrendingContent('https://github.com/trending/unknown?since=monthly'), 'github_unknown_monthly'],
  [getGithubTrendingContent('https://github.com/trending/markdown?since=daily'), 'github_markdown_daily'],
  [getGithubTrendingContent('https://github.com/trending/markdown?since=weekly'), 'github_markdown_weekly'],
  [getGithubTrendingContent('https://github.com/trending/markdown?since=monthly'), 'github_markdown_monthly'],
  [getGithubTrendingContent('https://github.com/trending/rust?since=daily'), 'github_rust_daily'],
  [getGithubTrendingContent('https://github.com/trending/rust?since=weekly'), 'github_rust_weekly'],
  [getGithubTrendingContent('https://github.com/trending/rust?since=monthly'), 'github_rust_monthly'],
]

module.exports = {
  actions,
}
